### PR TITLE
Initial python client library

### PR DESCRIPTION
**Pull request by walkah**
I believe this achieves both #1 and #2 (the library and the cli program). It's pretty heavily based on the PHP client library in openphoto-php. The one (minor) deviation is that the host parameter for the CLI is '-H' (rather than '-h') - since -h is reserved for showing the helptext by optparse. 

Cheers!

### CODE REVIEW

**Comment by jmathai** [comment]
Wowza! Awesome.

**Comment by walkah** [comment]
_bows_ happy to maintain it too, if you'd like!

**Comment by jmathai** [comment]
I'm not quite as familiar with Python but doesn't it have a CPAN like repository name PIP and Ruby gems? What's it take to add it there?

**Comment by walkah** [comment]
Yeah, there is http://pypi.python.org/pypi ... I can get it uploaded there. Then it's just a "pip install openphoto" away. ;-)

**Comment by jmathai** [comment]
Sweet :). And yes, if you're down to maintain the library that is awesome.

**Comment by walkah** [comment]
totally :)

**Pull request merged**
