### PR TITLE
Add support for config dotfiles

### LINKED ISSUE #5: use a dotfile (optionally) vs forcing secrets to live in the environment
Currently the openphoto script gets the credentials from rather generically-named environment variables:

https://github.com/openphoto/openphoto-python/blob/master/README.markdown

If you're very often running this program, it is probably better to have these secrets live in a dotfile instead of having a two-step process to run the script (source a script then run openphoto).  I would advise looking for a dotfile, e.g. $HOME/.openphoto, which contains the credentials and overriding from the environment if the environment variables exist

### PR DESCRIPTION
**Pull request by sneakypete81**
To close #5.

The config file can include the host name (overridable using the -H switch).

I was unsure whether to retain environment variable support too - I eventually decided to remove it to avoid confusion (as per @jmathai's comment: https://github.com/photo/openphoto-python/issues/5#issuecomment-3609710). Let me know if you think I should put it back.

### CODE REVIEW

**Comment by jmathai** [comment]
Looks good. I made one comment on one of the print lines
https://github.com/sneakypete81/openphoto-python/commit/3918b83c1c1dac20351f1e0f5ef7d7455d356d1e#commitcomment-2638521

// cc @walkah

**Comment by sneakypete81** [comment]
Good point - I've updated the documentation now too.

**Comment by walkah** [comment]
So, this pull request is out of date thanks to #13 

I think I suggested this before, but @jmathai I would be in favour of using proper "ini" syntax. We could use sections for different instances (e.g. I have my dev environment, my trovebox account and a self-hosted version). 

We can then use the battle-tested ConfigParser. Thoughts?

**Comment by jmathai** [comment]
@walkah Yeah, that sounds good. It beats having a bunch of config files and sourcing the one you need.

**Comment by walkah** [comment]
I think so too. How does that sound to you, @sneakypete81 ?

Oh, I was thinking that the format wold be something like:

   [default] ; required
   consumerKey=680ad5ea14ae42b3a29ca95b69b326
   consumerSecret=91ce71e636
   token=02db36558883c09cc01aac1ac3d45e
   tokenSecret=18506814c6

   [mytrovebox] ;optional
   consumerKey=680ad5ea14ae42b3a29ca95b69b326
   consumerSecret=91ce71e636
   token=02db36558883c09cc01aac1ac3d45e
   tokenSecret=18506814c6

Then we could just have some sort of config switch that let you select which instance. If not specified, then use `default` - since the most common use case would be to only have 1 account.

**Comment by sneakypete81** [comment]
Sounds a nice idea, although there seemed to be general agreement in #5 that full-blown .ini was a step too far - simple key/value pairs are easier to handle in all languages. 

For "normal" users, a single definition in a dotfile is sufficient. In the case of multiple identities, selecting an alternative config file on the command line is not too arduous IMHO.

Happy to go either way, but we should probably continue this discussion in #5, as there was a good discussion going there. 

Also, it would be good to have the hostname specified in the config file.

**Comment by sneakypete81** [comment]
I've pushed a minor update to the --config/-c option. This now specifies a filename in the users config directory.

So If your ~/.config/openphoto directory contains the following config files:

```
    default
    test_site
    test2
```

Then you can switch between these profiles like so:

```
    openphoto -c test_site
    openphoto -c test2
```

Or specify a full path to a config file:

```
    openphoto -c /path/to/config_file
```

Or leave off the --config/-c option to use the default profile.

I think this provides the flexibility of the multi-profile .ini format without the multi-language parsing headaches.

**Comment by sneakypete81** [comment]
One more update to use the ConfigParser library as @walkah suggested.

Ready to merge now, I think - any objections?

**Pull request merged**
