### PR TITLE
Fixing unit tests for the multipart code (redux)

### PR DESCRIPTION
**Pull request by jmathai**
Removing tests with visibility since that's been deprecated.

### CODE REVIEW

**Comment by sneakypete81** [comment]
@jmathai: Your changes look good to me. So good in fact that I'd actually previously done them as part of #18.

I'd suggest closing this PR and merging #18 instead, since it also includes other tweaks to support the new API.

This is my bad for raising so many PRs in parallel. If they all look good to you and @walkah, I'll set about merging them in the next couple of days. The priority is #18, since without that the tests will fail on the current hosted site.

Does that sound ok?

**Comment by sneakypete81** [comment]
Closing, since these fixes have now been merged from #18

**Comment by sneakypete81** [comment]
@jmathai: I think it's safe to delete the multipart-tests branch now, since the proposed changes have now all been merged via PR #18 .

But let me know if I've misunderstood - GitHub does allow deleted branches to be restored.

**Comment by jmathai** [comment]
@sneakypete81 That's fine with me. (I do see a "restore" link, btw).

**Pull request closed without merging**
