### PR TITLE
Make the library more Pythonic 

### PR DESCRIPTION
**Pull request by sneakypete81**
Here's an implementation of a more Pythonic interface to the OpenPhoto API. There's quite a bit to this, so feel free to cherry-pick whatever is useful, or suggest improvements, (or a totally different approach!).

To make it more extensible, I've split __init__.py into:
- A bare **__init__,py** that just pulls in stuff from:
  - **openphoto_http.py** : low-level HTTP routines, and parameter/response processing
  - **api_photo.py** : methods for photo API endpoints (photos_list(), photo_update(), etc)
  - **api_tags.py** : same for tags
  - ...
- **objects.py** : classes enapsulating individual objects (Photos, Tags, etc)

I haven't implemented everything in the API, but I've made a start on the most common functions (listing and updating photos, tags, albums). I've been using this successfully over the past few days - the OpenPhoto API is very usable and logical.

The old-style .get and .post functions are still there, and operate in a similar manner as before, apart from a few tweaks to make them easier to work with:
- Parameters are passed in as keywords rather than a single dictionary
- Lists and boolean parameters are handled correctly
- The HTTP response is (optionally) parsed to a dict
- Error response codes (optionally) raise exceptions

The main.py commandline function is functionally unchanged.

### CODE REVIEW

**Comment by sneakypete81** [comment]
I'm still thinking through this a bit, and am leaning towards a slightly different structure where the various API types are members of the main class.

So instead of:

   photos = client.photos_list()

you'd do:

   photos = client.photos.list()

This seems a bit more logical to use than the arbitrary underscore. I'll apply this, write some tests, then let you know when it's ready to review.

**Comment by walkah** [comment]
Thanks for the update - I'll hold off on reviewing more deeply until you've added those changes. I agree - they read a bit better and should keep the code nice and clean. Thanks again!

**Comment by sneakypete81** [comment]
@walkah : sorry for the delay and large number of commits! I guess it wasn't really ready when I first opened the pull request.

I think it's ready for a review now, please let me know if anything needs clarifying or ripping up.

**Comment by sneakypete81** [comment]
@walkah : Just a reminder that this is now ready for review.
I realise there's a lot here, so feel free to suggest changes or ask if anything's unclear.

**Comment by mcepl** [comment]
Just drive-by comment. Looking at

> you'd do:
> 
> photos = client.photos.list()

it seems obvious, that I would prefer

```
photos = client.photos
```

(meaning, that it could be a property, which would be of the type list; are you expecting that client.photos could return some other type as well?)

**Comment by sneakypete81** [comment]
Overall, the idea is to use exactly the same endpoint structure as the official Openphoto API. I'll try to make this clearer in the docs, and specifically refer to the API documentation too. 

Also, Python attribute accesses should return immediately, so anything requiring a server access is best done as a function call (plus it allows parameters to be passed as part of the API call).

Thanks for your ideas though.

**Comment by sneakypete81** [comment]
@walkah, @jmathai: any progress on this? The recent Trovebox (fabrizio1.0) update introduced a new rev of the API, which requires a few tweaks, but this pull request is starting to get rather large! 

Since the API is still maturing, I suspect I'll be making a number of small tweaks to keep up. Feeling out the best way forward, some options are:

1) I'm happy to abandon this PR and create my own library somewhere else, if you'd like to keep the "official" Python library as a simple GET/POST wrapper. But I do think there's some value in having a "fully wrapped" Python API library.

2) If there are elements to this pull request that you'd like me to modify before merging, I'd appreciate any comments.

3) I'm happy to step up as an openphoto-python maintainer if required (but don't want to step on any toes :-)

**Comment by walkah** [comment]
Hey there - thanks for your persistence on this one!

I like the direction a lot, and am happy to merge this and move forward in this direction. I know, however, from previous discussions that @jmathai wanted to keep the API implementations as similar as possible across languages.

@jmathai is that still the case? Or, can we go in this direction with python and work on the others to catch them up for richer implementations?

**Comment by jmathai** [comment]
@walkah I don't believe it's still the case. The value is low for keeping everything to a lowest common denominator.

I think as a developer you would be happier with a richer tool that works for your language of choice than knowing it works the same as other languages you don't care about.

Perhaps it was a good idea, once upon a time. I doubt it though.

**Comment by jmathai** [comment]
That was a cryptic way of saying to merge the changes as you see fit :)

**Comment by sneakypete81** [comment]
I have a few PRs queued up waiting for this to go through:
- Adding support for API updates in the fabrizio1.0 branch (currently the code in this PR supports the frontend/master branch only)
- Improved logging
- Support for photo.transform

I could roll them all into this one, but I think it's cleaner to wait for this PR to be merged first.

**Comment by jmathai** [comment]
@walkah Did you want to go ahead and merge this sucker?

**Comment by walkah** [comment]
Heck yeah I do :+1:

**Comment by sneakypete81** [comment]
Ta!

**Pull request merged**
